version: '3.1'

services:

  postgres:
    container_name: postgres
    image: "postgres:13.0"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wikiDB
    ports:
      - 5432:5432
