version: "3.8"

services:
  wiki_db:
    container_name: "wiki_db"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wiki
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ./wiki_db_data:/var/lib/postgresql/data
      - ./wiki_db_log:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - wiki

networks:
  wiki:
    driver: bridge
