version: "3.8"

services:
  webserver:
    container_name: "webserver"
    image: nginx:latest
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - wiki
  certbot:
    container_name: "certbot"
    image: certbot/certbot:latest
    depends_on:
      - webserver
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - wiki
  wiki_db:
    container_name: "wiki_db"
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ./wiki_db_data:/var/lib/postgresql/data
      - ./wiki_db_log:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - wiki
  wiki_lake_fs_storage:
    container_name: "wiki_lake_fs_storage"
    image: treeverse/lakefs:1.0.0
    restart: always
    volumes:
      - ./wiki_lake_fs_storage_data:/home/lakefs/lakefs
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - lakefs run --local-settings
    networks:
      - wiki

networks:
  wiki:
    driver: bridge
