FROM python:3.11.3-slim-buster

COPY ../backend/requirements.txt ./app/requirements.txt
COPY ../backend/wiki ./app/wiki

RUN pip install -r ./app/requirements.txt

ENV PYTHONPATH=./app

EXPOSE 8000

CMD ["python", "./app/wiki/main.py"]
